/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_teste;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author w.rocha
 */
public class Projeto_17_CRUD extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Projeto_17_CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jText_Modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jtxt_DTfabricacao = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        Jtxt_IDflauta1 = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Jtxt_IDflautaPesquisada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jtxt_IDflautaPesquisar1 = new javax.swing.JTextField();
        jLabelDeletarFlauta = new javax.swing.JLabel();
        jTxt_flautaCadastrada = new javax.swing.JTextField();
        jButtonDeletar = new javax.swing.JButton();
        seletorDeArquivos = new javax.swing.JFileChooser();
        usuario_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setText("ID flauta");

        jLabel5.setText("Ano de fabricação");

        jLabel6.setText("Modelo");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        Jtxt_IDflauta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_IDflauta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Jtxt_DTfabricacao)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jText_Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(Jtxt_IDflauta1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtxt_IDflauta1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(Jtxt_DTfabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonAtualizar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jButtonDelete.setText("Pesquisar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel7.setText("Pesquisar_IDflauta");

        Jtxt_IDflautaPesquisada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_IDflautaPesquisadaActionPerformed(evt);
            }
        });

        jLabel8.setText("Marca Buscada:");

        Jtxt_IDflautaPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_IDflautaPesquisar1ActionPerformed(evt);
            }
        });

        jLabelDeletarFlauta.setText("Deletar flauta cadastrada");

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        seletorDeArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeArquivosActionPerformed(evt);
            }
        });

        usuario_img.setText("img_aqui");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(seletorDeArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuario_img)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Jtxt_IDflautaPesquisada, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete)
                            .addComponent(jLabel8)
                            .addComponent(Jtxt_IDflautaPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDeletarFlauta)
                            .addComponent(jTxt_flautaCadastrada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeletar))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelDeletarFlauta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtxt_IDflautaPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_flautaCadastrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonDeletar))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_IDflautaPesquisada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuario_img)
                .addGap(63, 63, 63)
                .addComponent(seletorDeArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null; //concertado para statement

            String url =  "jdbc:mysql://localhost:3306/teste";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection(url,usuario,senha);
            String sql = "UPDATE flauta SET ano_fabricacao = ?, Marca = ? WHERE ID_flauta = ? ";
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Jtxt_DTfabricacao.getText()); //
            statement.setString(2, jText_Modelo.getText()); // 
            statement.setString(3, Jtxt_IDflauta1.getText()); // 

            System.out.println("Deu certo");
            
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Projeto_17_CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void Jtxt_IDflautaPesquisadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_IDflautaPesquisadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_IDflautaPesquisadaActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null; //concertado para statement

            String url =  "jdbc:mysql://localhost:3306/teste";

            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection(url,usuario,senha);
            String sql = "INSERT INTO flauta ( ID_flauta, ano_fabricacao, Marca) VALUES (?, ?, ?)";
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Jtxt_IDflauta1.getText()); // nome do bebe
            statement.setString(2, Jtxt_DTfabricacao.getText()); // data de nascimento
            statement.setString(3, jText_Modelo.getText()); // nome dos pais

            System.out.println("Deu certo");
            
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jPanel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3AncestorAdded

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/teste";
            String user = "root";
            String password = "";
            
            conexao = DriverManager.getConnection (url, user, password) ;
            String sql = "SELECT Marca FROM flauta WHERE ID_flauta = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Jtxt_IDflautaPesquisar1.getText());

            ResultSet resultSet =  statement.executeQuery();
            if(resultSet.next()){
                try {
                    String Modelo = resultSet.getString("Marca");
                    Jtxt_IDflautaPesquisada.setText(Modelo);
                } catch (SQLException ex) {
                    Logger.getLogger(Projeto_17_CRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                Jtxt_IDflautaPesquisada.setText("Modelo não encontrado.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Projeto_17_CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void Jtxt_IDflauta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_IDflauta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_IDflauta1ActionPerformed

    private void Jtxt_IDflautaPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_IDflautaPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_IDflautaPesquisar1ActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/teste";
            String user = "root";
            String password = "";
            
            conexao = DriverManager.getConnection (url, user, password) ;
            String sql = "DELETE FROM flauta WHERE ID_flauta = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jTxt_flautaCadastrada.getText());
            
            statement.executeUpdate();
            
            System.out.println("Deu certo! :)");
            
        } catch (SQLException ex) {
            Logger.getLogger(Projeto_17_CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void seletorDeArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeArquivosActionPerformed
        // TODO add your handling code here:
        seletorDeArquivos.setVisible(true);
        
        int result = this.seletorDeArquivos.showOpenDialog(this.usuario_img);
        
        if (result == seletorDeArquivos.APPROVE_OPTION){
            
            String filePath = this.seletorDeArquivos.getSelectedFile().getAbsolutePath();
            ImageIcon icon = new ImageIcon(filePath);
            this.usuario_img.setIcon(icon);
            System.out.println("Caminho do arquivo: " + filePath);        }
            // usuario_img.setIcon(filePath);
    }//GEN-LAST:event_seletorDeArquivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto_17_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto_17_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto_17_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto_17_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto_17_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtxt_DTfabricacao;
    private javax.swing.JTextField Jtxt_IDflauta1;
    private javax.swing.JTextField Jtxt_IDflautaPesquisada;
    private javax.swing.JTextField Jtxt_IDflautaPesquisar1;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDeletarFlauta;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jText_Modelo;
    private javax.swing.JTextField jTxt_flautaCadastrada;
    private javax.swing.JFileChooser seletorDeArquivos;
    private javax.swing.JLabel usuario_img;
    // End of variables declaration//GEN-END:variables
}
